import yfinance as yf
from textblob import TextBlob
import requests
import os
from dotenv import load_dotenv

load_dotenv()  # This reads your .env file

def send_telegram_msg(message):
    TOKEN = "8724582515:AAEElkYDy06wM70CR9m9dASomqENsgmZfuY" # replace with your bot token
    CHAT_ID ="7965377966" # replace with your chat id

    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": message,
        "parse_mode": "Markdown"}  # this will allows for bold of italic texting style'''
    requests.post(url, data = payload)


def generate_morning_report(symbol):
    # 1. Get Price & Trend
    df = yf.download(symbol, period="30d")
    current_price = df['Close'].iloc[-1].item()
    sma_20 = df['Close'].rolling(20).mean().iloc[-1].item()
    trend = "🚀 BULLISH" if current_price > sma_20 else "📉 BEARISH"
    
    # 2. Get Sentiment (Simulated for this demo)
    # In production, you'd use your Scraper function here
    sentiment_score = 0.12 
    mood = "Optimistic" if sentiment_score > 0.1 else "Cautious"
    
    # 3. The Recommendation Logic
    action = "BUY/HOLD" if (current_price > sma_20 and sentiment_score > 0.05) else "WAIT/SELL"
    
    # 4. Construct the Briefing
    report = (
        f"☀️ *DAILY MARKET INTELLIGENCE: {symbol}*\n"
        f"--------------------------------\n"
        f"💰 *Price:* ${current_price:.2f}\n"
        f"📈 *Trend:* {trend}\n"
        f"🌍 *World Mood:* {mood} ({sentiment_score})\n\n"
        f"🎯 *ACTION:* `{action}`\n"
        f"--------------------------------\n"
        f"Generated by: Your AI Sentinel 🤖"
    )
    
    # 5. Send it!
    send_telegram_msg(report)
    print("✅ Morning Report sent to Telegram!")

# Run it!
generate_morning_report("GLD")